config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'session#index'

  resources :session do
    collection do
      #get 'edit/:user_id', to: "session#edit"
      get 'signup', to: "session#new"
      get 'login', to: "session#index"
      post 'login', to: "session#login"
      get 'dashboard', to: "session#dashboard"
      get 'logout', to: "session#logout"
      post 'social/login', to: "session#social_login"

      
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_user
    # helper_method :current_user 
    #     def current_user  
    #         @current_user ||= User.find_by(id: session[:user_id])
    #         if session[:user_id] 
    #     end
    # end

    #Authenticate
        def require_user  
            redirect_to login_session_index_path unless session[:user_id] 
        end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    layout "session"
    skip_before_action :require_user, only: [:index, :login, :new, :create, :social_login]

    def index 
        @user=User.new     
    end

    def login
        islogged=false
        if !params[:user][:email].blank? and !params[:user][:password].blank? 
            user = User.find_by(email: params[:user][:email])    
            if user and user.authenticate(params[:user][:password])
                session[:user_id]=user.id
                islogged=true
            end    
        end    
        if islogged
            redirect_to dashboard_session_index_path
        else 
            flash[:danger] = 'Invalid email/password combination' 
            @user=User.new
            render 'index'    
        end
    end    

    def dashboard
    end

    def new
        @user=User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to dashboard_session_index_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(session[:user_id])
    end

    def update
        @user = User.find(session[:user_id])
        @user.update(user_params)
        redirect_to dashboard_session_index_path
    end

  
    def logout
        session[:user_id] = nil
        flash[:success] = "Хэрэглэгч гарлаа"
        redirect_to login_session_index_path
    end 

    def social_login
        result=Hash.new
        result[:status]="ok"
        if  params[:user].present?
            user = User.find_by(email: params[:user][:email])
            if params[:user][:fb_id].present?
                user =  User.find_by(fb_id: params[:user][:fb_id])
            elsif params[:user][:email].present?
                user =  User.find_by(email: params[:user][:email])
            end
    
            if user.nil?
                user = User.new(social_user_params)
                password = SecureRandom.base64
                user.password=password
                user.password_confirmation=password
                
                user.save
            else
                user.update(social_user_params)
            end   
            session[:user_id] = user.id
            result[:url]=dashboard_session_index_path
        end
        render json: result

    end
  
    private
    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def social_user_params
        params.require(:user).permit(:name,:email,:fb_id, :user_type)
    end

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'session', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'session', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'facebook', 'data-turbolinks-track': 'reload' %>
  
    <%= javascript_include_tag 'google', 'data-turbolinks-track': 'reload' %>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="712150726072-b8jgpn9aldks623fs35r51gnabnqcen5.apps.googleusercontent.com">
    <meta name="google-signin-scope" content="profile email">
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/session/dashboard.html.erb
<%= javascript_include_tag 'facebook', 'data-turbolinks-track': 'reload' %>

dashboard

<!-- Logout field -->
<ul class="dropdown-menu">
<li>
  <%= link_to "Log out", logout_session_index_path, id:"sign_out" %>
</li>
</ul>

app/views/session/edit.html.erb
<%= stylesheet_link_tag    'edit', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<div id="login-box">
<div class="left-box">
    <h1>Хувийн мэдээлэл шинэчлэх</h1>
    <%= form_for(@user, url: session_path(id: session[:user_id]), method: "put") do |f| %>
        <% @user.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>

      <!-- Edit field -->

        <%= f.text_field :name, class: 'form-control', placeholder: "Хэрэглэгчийн нэр" %>
    
        <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
    
        <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>

        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Нууц үг дахин оруулах" %>
    
        <%= f.submit "Хадгалах", class: "btn btn-primary" %>
    <% end %>
</div>

<!-- Social media sign-in -->
<div class="right-box">
    <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>

<button class="social facebook">Facebook нэвтрэх</button>    
<button class="social twitter">Twitter нэвтрэх</button> 
<button class="social google">Google+ нэвтрэх</button> 
</div>
</div>

app/views/session/index.html.erb
<div id="login-box">
    <div class="left-box">
        <h1>Нэвтрэх</h1>
        <%= form_for(@user, url: login_session_index_path) do |f| %>

            <% flash.each do |key, value| %>
                <div>
                      <%= value %>
                </div>
          <% end %>
          
            <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
        
            <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>
        
            <%= f.submit "Нэвтрэх", class: "btn btn-primary" %>
        <% end %>
             <p>Шинэ хэрэглэгч? <%= link_to "Бүртгүүлэх", signup_session_index_path %></p>
    </div>
   
    <!-- Social media sign-in -->
               <div class="right-box">
            <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>               

            <div class="fb-login-button" onlogin="checkLoginState();" data-max-rows="1" data-size="large" data-button-type="login_with"  data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
            <a href="#" onclick="my_fb_logout()">Logout</a>

            <div class="g-signin2" data-width="236" data-height="40" data-longtitle="true" data-onsuccess="onSignIn" data-theme="dark"></div>
            <a href="#" onclick="signOut();">Sign out</a>

    </div>
</div>

app/views/session/new.html.erb
<div id="login-box">
<div class="left-box">
    <h1>Бүртгүүлэх</h1>
    <%= form_for(@user, url: session_index_path) do |f| %>
        <% @user.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>

      <!-- SignUp field -->
        <%= f.text_field :name, class: 'form-control', placeholder: "Хэрэглэгчийн нэр" %>

        <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
    
        <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>

        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Нууц үг дахин оруулах" %>
    
        <%= f.submit "Нэвтрэх", class: "btn btn-primary" %>
    <% end %>
</div>

<!-- Social media sign-in -->
<div class="right-box">
    <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>

<button class="social facebook">Facebook нэвтрэх</button>    
<button class="social twitter">Twitter нэвтрэх</button> 
<button class="social google">Google+ нэвтрэх</button> 
</div>
</div>